name: Fail Test with Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**
      - experiment/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker compose -f compose.test.failure.yaml build

      - name: Run failure test
        id: test
        continue-on-error: true
        run: |
          docker compose -f compose.test.failure.yaml up --exit-code-from test-with-docker

      - name: Upload test result to artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-result
          path: test-result

      - name: Check test result
        if: steps.test.outcome == 'failure'
        run: |
          echo "Test failed as expected"
          exit 1
