name: Fail Test with Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/**
      - experiment/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker compose -f compose.test.success.yaml build

      - name: Run failure test
        id: test
        continue-on-error: true
        run: |
          docker compose -f compose.test.success.yaml up --exit-code-from test-with-docker

      - name: Check test result
        if: steps.test.outcome == 'failure'
        run: |
          echo "Test failed as expected"
          exit 1